name: Build and Push Docker Image
description: Build and push Docker image to Azure Container Registry.

inputs:
  tag:
    description: Docker image tag to build and push
    required: true

runs:
  using: composite
  steps:
    - name: Login to Azure Container Registry
      shell: bash
      run: az acr login --name procosys

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/Equinor.Procosys.Library.WebApi/Dockerfile
        push: true
        tags: |
          procosys.azurecr.io/library/api:${{ inputs.tag }}
          procosys.azurecr.io/library/api:latest
