version: "3"

services: 
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      args:
        http_proxy: http://www-proxy.statoil.no:80
        https_proxy: http://www-proxy.statoil.no:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/746aa4e7-b5b6-4c4d-9166-e70307906525/:/root/.microsoft/usersecrets/746aa4e7-b5b6-4c4d-9166-e70307906525/