version: "3"

services: 
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/746aa4e7-b5b6-4c4d-9166-e70307906525/:/root/.microsoft/usersecrets/746aa4e7-b5b6-4c4d-9166-e70307906525/