name: 🐳 Build and Push Docker Image if Missing
description: Builds and pushes a Docker image to the Container Registry if it does not already exist.

inputs:
  tag:
    description: Docker image tag to check, build, and push
    required: true

runs:
  using: composite
  steps:
    - name: Check if image exists in ACR
      id: check-image
      uses: ./.github/actions/docker-check-if-image-exists
      with:
        tag: ${{ inputs.tag }}

    - name: Build and push image
      if: steps.check-image.outputs.image-exists == 'false'
      uses: ./.github/actions/docker-build-push
      with:
        tag: ${{ inputs.tag }}
