name: 🔁🏭 Deploy to Prod (Rollback)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref (commit SHA, tag, or branch) to roll back to
        required: true
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod-rollback
      radix-environment: prod
      ref: ${{ inputs.ref }}
    secrets: inherit
