name: 🚀🧪 Deploy to Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
      radix-environment: test
      branch: ${{ github.ref_name }}
    secrets: inherit
