name: 🚀 Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        description: GitHub environment name (dev, test, prod)
        required: true
        type: string
      radix-environment:
        description: Radix environment name
        required: true
        type: string
      branch:
        description: Git branch to build and deploy
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy to Radix - ${{ inputs.radix-environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Print input values
        shell: bash
        run: |
          echo "environment: ${{ inputs.environment }}"
          echo "radix-environment: ${{ inputs.radix-environment }}"
          echo "branch: ${{ inputs.branch }}"

      - uses: actions/checkout@v4

      - name: Authenticate with Radix
        uses: equinor/radix-github-actions@v2
        with:
          azure_client_id: ${{ vars.AZURE_CLIENT_ID }}

      # TODO fix application
      - name: Build and deploy via Radix CLI
        shell: bash
        run: |
          rx create pipeline-job build-deploy \
            --application procosys-library-api-build-test \
            --context playground \
            --branch ${{ inputs.branch }} \
            --environment ${{ inputs.radix-environment }} \
            --follow
